# Generated by Django 5.1.2 on 2024-10-29 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=20)),
                ('color_en', models.CharField(max_length=20, null=True)),
                ('color_ru', models.CharField(max_length=20, null=True)),
                ('volume', models.DecimalField(decimal_places=1, max_digits=2)),
                ('year', models.PositiveIntegerField()),
                ('type_change', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('video', models.FileField(blank=True, null=True, upload_to='vid/')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=32)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.marka')),
            ],
        ),
    ]
